config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "/login", to: "sessions#login"
  get "/auth/google/callback", to: "sessions#callback"

  namespace :api do
    resources :activities, only: [:index, :create]
    resources :activity_parameters, only: [:index]
  end

  root to: "dashboard#index"
  match "*any", to: "dashboard#index", via: :all
end

app/models/activity.rb
# frozen_string_literal: true

class Activity < ApplicationRecord
  belongs_to :user
  belongs_to :menu
  belongs_to :store

  class << self
    def parameters
      {
        menu: menu_params,
        store: store_params,
        size: size_params,
        yasai: yasai_params,
        abura: abura_params,
        ninniku: ninniku_params,
        karame: karame_params,
      }
    end

    private
    def menu_params
      Menu.all.map do |m|
        {
          id: m.id,
          value: m.id,
          label: m.name,
        }
      end
    end

    def store_params
      Store.all.map do |m|
        {
          id: m.id,
          value: m.id,
          label: m.name,
        }
      end
    end

    def size_params
      [
        {
          id: 1,
          value: 'small',
          label: '小',
        },
        {
          id: 2,
          value: 'large',
          label: '大',
        },
      ]
    end

    def yasai_params
      [
        {
          id: 1,
          value: 'small',
          label: '小',
        },
        {
          id: 2,
          value: 'normal',
          label: 'ノーコール',
        },
        {
          id: 3,
          value: 'large',
          label: 'マシ',
        },
        {
          id: 4,
          value: 'mashimashi',
          label: 'マシマシ',
        },
      ]
    end

    def abura_params
      [
        {
          id: 1,
          value: 'small',
          label: '小',
        },
        {
          id: 2,
          value: 'normal',
          label: 'ノーコール',
        },
        {
          id: 3,
          value: 'large',
          label: 'マシ',
        },
        {
          id: 4,
          value: 'mashimashi',
          label: 'マシマシ',
        },
        {
          id: 5,
          value: 'crazy',
          label: 'ザブトン',
        },
      ]
    end

    def ninniku_params
      [
        {
          id: 1,
          value: 'small',
          label: '小',
        },
        {
          id: 2,
          value: 'normal',
          label: 'ノーコール',
        },
        {
          id: 3,
          value: 'large',
          label: 'マシ',
        },
        {
          id: 4,
          value: 'mashimashi',
          label: 'マシマシ',
        },
      ]
    end

    def karame_params
      [
        {
          id: 1,
          value: 'small',
          label: '小',
        },
        {
          id: 2,
          value: 'normal',
          label: 'ノーコール',
        },
        {
          id: 3,
          value: 'large',
          label: 'マシ',
        },
        {
          id: 4,
          value: 'mashimashi',
          label: 'マシマシ',
        },
      ]
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/menu.rb
# frozen_string_literal: true

class Menu < ApplicationRecord
  has_many :activities
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  has_many :activities
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :activities

  validates :name, presence: true
  validates :email, presence: true

  class << self
    def find_for_google(auth_hash)
      user = User.find_or_create_by(email: auth_hash.info.email) do |u|
        u.name = auth_hash.info.name
      end
      user
    end
  end
end

app/controllers/activities_controller.rb
# frozen_string_literal: true

class ActivitiesController < ApplicationController
  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new
    store_id = params["activity"]["store_id"]
    menu_id = params["activity"]["menu_id"]
    size = params["activity"]["size"]
    yasai = params["activity"]["yasai"]
    ninniku = params["activity"]["ninniku"]
    abura = params["activity"]["abura"]
    karame = params["activity"]["karame"]
    calorie = params["activity"]["calorie"]

    @activity.user_id = current_user.id
    @activity.store_id = store_id
    @activity.menu_id = menu_id
    @activity.size = size
    @activity.yasai = yasai
    @activity.ninniku = ninniku
    @activity.abura = abura
    @activity.karame = karame
    @activity.calorie = calorie

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: "activity was successfully created." }
        format.json { render "", status: :created, location: @activity }
        format.js { @status = "success" }
      else
        format.html { render "" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
        format.js { @status = "fail" }
      end
    end
  end
end

app/controllers/api/activities_controller.rb
# frozen_string_literal: true

class Api::ActivitiesController < Api::ApplicationController
  before_action :check_login

  def index
    activities = Activity.includes(:store).includes(:menu).where(user_id: current_user.id).order(created_at: "DESC")
    render json: activities
  end

  def create
    payload = ActivityPayload::Create.new(params, current_user.id)
    if payload.valid?
      activity = Activity.create!(payload.to_h)
      render json: activity
    else
      render_422(payload.errors)
    end
  end
end

app/controllers/api/activity_parameters_controller.rb
# frozen_string_literal: true

class Api::ActivityParametersController < Api::ApplicationController
  before_action :check_login

  def index
    render json: Activity.parameters
  end
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

class Api::ApplicationController < ApplicationController
  def check_login
    return render json: {}, status: :unauthorized unless is_login?
  end

  def render_422(errors = "Unprocessable Entity")
    render json: { errors: errors }, status: :unprocessable_entity
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def check_login
    unless is_login?
      session[:redirect_path] = request.fullpath
      redirect_to login_path
    end
  end

  def is_login?
    session[:user_id].present?
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :check_login

  layout "spa_page"

  def index; end
end

app/controllers/root_controller.rb
# frozen_string_literal: true

class RootController < ApplicationController
  before_action :check_login

  def index
    @activities = current_user.activities.all
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def login; end

  def callback
    auth_hash = request.env["omniauth.auth"]
    user = User.find_for_google(auth_hash)
    redirect_path = session[:redirect_path] || root_url

    reset_session
    session[:user_id] = user.id
    flash[:success] = "ログインに成功しました"

    redirect_to redirect_path
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def assets_path(path)
    return webpack_dev_server_path(path) if Rails.env.development? || Rails.env.test?
    manifest = Rails.application.config.assets_manifest
    path = manifest[path] if manifest && manifest[path].present?
    "/dist/#{path}"
  end

  private

  def webpack_dev_server_path(path)
    "http://localhost:4000/#{path}"
  end
end

app/views/activities/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="page--header">アクティビティ作成</div>
    <%= form_for(@activity, remote: true) do |f| %>

        <div class="form-group">
            <%= f.label :store_id, "店名", class: "col-sm-4 control-label"  %><br />
            <div class="col-sm-10">
                <%= f.collection_select :store_id, Store.all, :id, :name, {}, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label :menu_id, "メニュー", class: "col-sm-4 control-label"  %><br />
            <div class="col-sm-10">
                <%= f.collection_select :menu_id, Menu.all, :id, :name, {}, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label 'サイズ', class: "col-sm-4 control-label"  %><br />
            <div class="col-sm-10">
                <%= f.select(:size, { '小なめ' => 'small', '多め' => 'large' }, label: '麺の量') %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label '野菜の量', class: "col-sm-4 control-label"  %><br />
            <div class="col-sm-10">
                <%= f.select(:yasai, { '小なめ' => 'small', 'ノーコール' => 'normal' , 'マシ' => 'large' ,'マシマシ' => 'huge' }, label: '野菜の量') %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label 'にんにくの量', class: "col-sm-4 control-label"  %><br />
            <div class="col-sm-10">
                <%= f.select(:ninniku, { '小なめ' => 'small', 'ノーコール' => 'normal' , 'マシ' => 'large' ,'マシマシ' => 'huge'  }, label: 'にんにくの量') %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label 'アブラの量', class: "col-sm-4 control-label"  %><br />
            <div class="col-sm-10">
                <%= f.select(:abura, { '小なめ' => 'small', 'ノーコール' => 'normal', 'マシ' => 'large', 'マシマシ' => 'huge', 'ザブトン' =>'crazy' }, label: 'アブラの量') %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label ' カネシの量', class: "col-sm-4 control-label"  %><br />
            <div class="col-sm-10">
                <%= f.select(:karame, { '小なめ' => 'small', 'ノーコール' => 'normal' , 'マシ' => 'large' ,'マシマシ' => 'huge'  }, label: 'カネシの量') %>
            </div>
        </div>

        <div class="form-group">
            <%= f.label 'カロリー', class: "col-sm-4 control-label"  %><br />
            <div class="col-sm-10">
                <%= f.text_field :calorie, class: "form-control" %>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <%= f.submit "作成", class: "btn btn-success btn-sm" %>
            </div>
        </div>

    <% end %>
  </div>
</div>

app/views/activities/_tr.html.erb
 <tr>
  <th><%= Store.find(activity.store_id).name %></th>
  <th><%= Menu.find(activity.menu_id).name %></th>
  <th><%= activity.created_at.in_time_zone('Asia/Tokyo').strftime("%Y/%m/%d %H:%M:%S") %></th>
</tr>

app/views/activities/create.js.erb
<% if @status == 'success' %>
    $("#activites_list").append("<%= j(render("tr", activity: @activity)) %>");
<%  elsif @status == 'fail' %>
    alert('error!');
<% end %>
$("#activity-modal").modal("hide");

app/views/activities/new.html.erb
とうろくかんりょうっ！

app/views/activities/new.js.erb
$("#activity-modal").html("<%= escape_javascript(render 'form') %>")
$("#activity-modal").modal("show")

app/views/dashboard/index.html.erb
<div id="root"></div>
<script type="text/javascript">
    window.csrfToken = <%= raw form_authenticity_token.to_json %>
</script>
<script src="<%= assets_path('main.js') %>"></script>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="logo">
    <div class="logo--description">
      お前は今まで食べた麺の量を覚えているか？
    </div>
    <div class="logo--main">
      二郎 LifeLog
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JiroLifelog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/no_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>二郎Lifelog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/spa_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JiroLifelog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/_counter_pannels.html.erb
<div class="counter">
  <div class="counter--header">
    今月の活動統計
  </div>
  <div class="counter--body">
    <div class="counter--body--item">
      <div class="counter--body--item--title">
        食べた量 
      </div>
      <div class="counter--body--item--body" >
        1000
      </div> 
      <div class="counter--body--item--unit">
        杯
      </div>
    </div>
    <div class="counter--body--spacer"></div>
    <div class="counter--body--item">
      <div class="counter--body--item--title">
        総カロリー
      </div>
      <div class="counter--body--item--body">
        10000 
      </div>
      <div class="counter--body--item--unit">
        kcal
      </div>
    </div>
    <div class="counter--body--spacer"></div>
    <div class="counter--body--item">
      <div class="counter--body--item--title">
        踏破店舗
      </div>
      <div class="counter--body--item--body" >
        30
      </div>
      <div class="counter--body--item--unit">
        店舗
      </div>
    </div>
  </div>
</div>

app/views/root/index.html.erb
<div class="container">

  <%= render 'counter_pannels' %>
  
  <div class="list">
    <div class="list--title">あなたの食事履歴</div>
    <div class="list--cation">
      <%= link_to '詳細', '#', class: "btn btn-warning" %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>店舗</th>
          <th>メニュー</th>
          <th>日付</th>
        </tr>
      </thead>
      <tbody id="activites_list">
        <% @activities.each_with_index do |a, i|%>
          <tr>
            <th><%= Store.find(a.store_id).name %></th>
            <th><%= Menu.find(a.menu_id).name %></th>
            <th><%= a.created_at.strftime("%Y/%m/%d %H:%M:%S") %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="list">
    <div class="list--title">あなたの称号履歴</div>
    <div class="list--cation">
      <%= link_to '詳細', '#', class: "btn btn-warning" %>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>称号</th>
          <th>取得日付</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th>初二郎！</th>
          <th>2018/05/18</th>
        </tr>
        <tr>
          <th>池袋店踏破！</th>
          <th>2018/05/18</th>
        </tr>
        <tr>
          <th>新宿店踏破！</th>
          <th>2018/05/31</th>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<%= link_to '追加', new_activity_path, remote: true, class: "floating-action-button" %>

<div id="activity-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>